//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("ChilliSource Mobile")]
[assembly: AssemblyVersion("0.1.0")]
[assembly: AssemblyFileVersion("0.1.0")]
[assembly: AssemblyInformationalVersion("0.1.0+4.Branch.master.Sha.d0b3186552274a97e58e26d0e463e2f04fe48764")]
[assembly: AssemblyCopyright("Copyright (c) BlueChilli Technology PTY LTD")]

