platform :ios, '9.3'
install! 'cocoapods', :integrate_targets => false
target 'ObjectiveSharpieIntegration' do
  use_frameworks!
end
pod 'ICGVideoTrimmer', :git=> 'https://github.com/BlueChilli/ICGVideoTrimmer'


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = "NO"
    end
  end
end